### ISSUE TITLE
[Hackintosh] 我的黑苹果配置分享

### ISSUE THREAD

**Issue by BenjaminX** [BenjaminX/BenAlwaysTalkShit#4]
# [Hackintosh] 我的黑苹果配置分享

预判这篇文会比较杂乱，算一个小小的总结。去年阴差阳错的玩了一把 hackintosh 黑苹果，作为一个忠实的果粉内心是抵制的。但是，这几年 Apple 家产品上出的那些问题，就不在此多提了，果粉们都应该知道的。（我不会告诉你我的 MacBook Pro (15-inch, Late 2016)，除了主板没修其它 Apple Store 全给我换了一遍）

去年先发现一个德国佬搞的 ozmosis 这东西，传说最接近白苹果的黑苹果方案，就此踏上 hackintosh 不归路。但是，此方案已经被我放弃。
原因主要三个：
1. 基于 BIOS 修改，来回刷主板 BIOS 很烦。自己制作修改 BIOS ROM 文件风险高难度大，刷主板门槛也略高普通用户很难搞定。
2. 这货不是开源的，并不支持最新的 CPU 系列，最终稳定状态只支持到 Intel 4 代 CPU（Haswell）。
3. 使用下来优势也并不明显，并且稳定性也存疑。（刷坏了一次主板）

然后就是现在通用最佳方案 clover 黑苹果，clover 是现在阶段最流行也最成熟的方案，配置做的好几乎和白苹果无差别。此方案和以前的方案类似，会从硬盘上的 EFI 分区上加载（技术细节就不在此展开了），带来的好处升级更新方便（一个 pkg 包装一下就行了），维护活跃几乎2-3 天就有新版 release，紧跟 masOS 版本更新节奏。我是不能接受 Hackintosh 不能更新系统的😁

好了，说正事儿关于 hackintosh 需要注意的几点

硬件：
* 第一原则选 Intel CPU，AMD 不要碰。
* 第二原则选技嘉主板，不要用华硕。
* 第三原则显卡一定要选 ATI 的，此处 NVIDIA 无解，macOS 10.14.x 之后驱动都没有，据说是 Apple 一直卡着 NVIDIA 不给驱动包授权签名。
* 硬盘 SSD 选三星的 Pro 系，不要搞其它的自寻烦恼。
* 无线网卡、蓝牙这个很关键。直接到淘宝买 BCM943602CS 转接做好的卡，这款卡 macOS 免驱直接驱动。直接决定 macOS 的使用体验，例如 Handoff、AirDorp 等都依赖网卡，想要无缝使用必须买这个卡少很多的麻烦。

好了差不多就这些要点了，具体怎么选就直接去最知名的 https://www.tonymacx86.com 查 Buyer’s Guide 吧，看着自己的钱包下单。
总体来说，只要硬件不乱买按照 Guide 中的来配置黑苹果效果都不会差，性价比是很划算的。

软件：
* 不用自己下最新的 macOS 镜像制作集成 clover 版本，这里推荐一个老 geek 的 blog [黑果小兵的部落阁](https://blog.daliansky.net) 直接用他做好的 macOS IMG 包很好用，装好了系统再来升级调整配置会更简单。
* 下载安装 Clover Configurator [下载链接](https://mackie100projects.altervista.org/download-clover-configurator/)  后续调整配置很多东西时都会用到这个工具，加载 EFI 分区中 CLOVER 目录 config 文件做配置调整。
* 这几位 hackintosh 圈的大神地址需要记录一下，后续需要的很多 kext 扩展和修复都出自他们之手。[Acidanthera](https://github.com/acidanthera)  [RehabMan](https://bitbucket.org/%7Be26fb9ce-5cc2-4e36-8576-7a8faae8e194%7D/)
* clover 日常更新发布地址 [Link](https://github.com/Dids/clover-builder/releases) 几乎每天都在发布新版。经验来说，每次 macOS 发布更新后等 2-3 天，升级前下载一个最新版本 clover 安装好，然后再升级 macOS 就没问题了。PS，不要顺序搞反了，后果很严重。

这里也顺带分享一下我的机器配置清单：
CPU：Intel Core i7-4790K
主板：技嘉 Gigabyte Z97X-UD3H rev 1.2
显卡：迪兰 Dataland RX580 8G X-Serial 战神
硬盘：三星  960 Pro 512GB SSD M.2
网卡：BCM943602CS
内存：海盗船 复仇者 Pro DDR3 2400 4 * 8GB = 32GB

这套配置的 EFI 全套也打包放一个，配置相同的情况直接替换就可以使用，支持最新的 macOS 10.14.5 (18F132) 。能不能直接用主要就看主板和显卡情况而定。EFI [下载链接](https://github.com/BenjaminX/benjaminx.github.io/raw/master/Hackintosh/EFI20190702.zip)，后续有更新我也会同步跟进。这台 Hackintosh 现在作为辅机使用，有些时候测试一些新东西都在这台机器了。如果稳定性持续做到两次大版本 macOS 升级都可以无痛升级，准备主力机都切换到 Hackintosh 了，MBP 做备机，出门带 iPad Pro。

总结，这一套折腾下来也有大半年多了，换了 clover 后一切都算稳定，出现过一次升级失败和一次死机。性价比极高，使用体验和白苹果的 iMac 没有差别。总体来说感觉直接黑苹果作为固定场所的机器使用已经没有问题了，稍微有一些动手能力完全可以折腾一下。

PS，WWDC 2019 后 Apple 应该知道了自己的错误，在 Pro 产品这个层面应该会回到自己的专长上面来。期待后续的 Apple Pro 系产品。
PPPPS，最新新闻首席工业设计 VP 伟大的马桶设计师 Ive 离开 Apple 了，一个新的 Apple 时代就要开始了。

**Comment by BenjaminX** [comment]
补充一个 Clover 最新版本地址，此地址为官网地址。
https://sourceforge.net/p/cloverefiboot/code/HEAD/log/?path=

国内论坛也有自己最新编译版本更新
http://bbs.pcbeta.com/viewthread-1740837-1-1.html

**Comment by yufengkz** [comment]
你好，有z97 4790k 1080显卡的配置吗？

**Comment by BenjaminX** [comment]
> 你好，有z97 4790k 1080显卡的配置吗？

NV 的卡官方就不支持了，不用折腾这个。

**Comment by BenjaminX** [comment]
已弃坑，配套硬件已出，不再更新。
新的黑果坑见这里 https://github.com/BenjaminX/Hackintosh-Gigabyte-Z390M-GAMING
